on:
  workflow_dispatch:

jobs:
  capture-unknowns:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.0'
    - run: |
        go run .
        cat results/* > all.csv
    - uses: actions/upload-artifact@v4
      with:
        name: results
        path: all.csv
